### ISSUE TITLE
Composer can not install bileto/cronner 

### ISSUE THREAD

**Issue by SlavaAurim** [bileto/cronner#69]
... because there is not this package on the packagist.com

Please, register package bileto/cronner or add to readme install instruction by old name:  
`composer require stekycz/cronner`

**Comment by jspetrak** [comment]
@SlavaAurim I am now following up with Packagist support on this. There is no user option to change to package name on the packagist.org, and also I can't create a new package because this repository is also associated with the old name.

**Comment by jspetrak** [comment]
@SlavaAurim Could be fixed now. We have resubmitted the package as a "new" repository.

https://packagist.org/packages/bileto/cronner

Please let me know if the issue persists.

**Comment by SlavaAurim** [comment]
Good!
